export enum GoalCategory {
  FITNESS = 'FITNESS',
  LEARNING = 'LEARNING',
  CAREER = 'CAREER',
  HEALTH = 'HEALTH',
  PRODUCTIVITY = 'PRODUCTIVITY',
  MINDFULNESS = 'MINDFULNESS',
  PERSONAL = 'PERSONAL',
  CUSTOM = 'CUSTOM',
}

export enum DifficultyPreference {
  EASY = 'EASY',
  NORMAL = 'NORMAL',
  HARD = 'HARD',
}

export enum TaskType {
  DAILY_HABIT = 'DAILY_HABIT',
  RECURRING_TASK = 'RECURRING_TASK',
  WEEKLY_GOAL = 'WEEKLY_GOAL',
  ONE_TIME_TODO = 'ONE_TIME_TODO',
  NUMERICAL_GOAL = 'NUMERICAL_GOAL',
}

export enum TaskFrequency {
  DAILY = 'DAILY',
  SPECIFIC_WEEKDAYS = 'SPECIFIC_WEEKDAYS',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  EVERY_N_DAYS = 'EVERY_N_DAYS',
  ONE_TIME = 'ONE_TIME',
}
